// Legende:
// #  Wand            .  Boden          P  Spielerstart     M  Monster-Start
// B  Batterie        G  Generator      E  Ausgangstor      X  Ausgang
// L  Deckenlampe     K  Spind          N  Notiz / Tonband
// a/b/c  Hebel       1/2/3  Tür, die vom passenden Hebel geöffnet wird (Hebel steht direkt daneben)
// O  Käfig mit The Tailor  Y  Vitrine mit der Puppe Mila
// D  Batterie auf einer Kommode mit Puppe (neben dem Käfig)
// Bereich „Die Nähstube“ (gehört zu Kapitel 1): X = Übergang (Tor schließt sich), Q = Schlüsselkarte,
// Z = Sicherheitstür (braucht die Karte), V = Lüftung (Zipper kommt heraus), F = Aufzug (Ziel)
// Bereich „Die Montagehalle“: W = Grube, S = Sicherung, U = Sicherungskasten, J = zweite Lüftung, d/4 = Hebel/Tür,
//   f = kaputter Aufzug, H = Lagertor (öffnet nach dem Sicherungskasten), h = Übergang ins Lager (Tor schließt sich)
// Bereich „Das Spielzeuglager“: R = Regal, C = Zahlenwürfel (Code), T = Zahlenschloss, 5 = Code-Tür, v = Lüftung
// Bereich „Das Spielzimmer“: k = Übergang, A = Stromspule, I = Empfänger, 6 = Strom-Tür, u = Lüftung
// Bereich „Der Förderband-Tunnel“: e = Start der letzten Verfolgungsjagd, F = Lastenaufzug (Ziel)
export const MAP = [
  "###################",
  "######L.PB#########",
  "######KY.B#########",
  "########.##########",
  "#######K.N#########",
  "#..K####.######K.O#",
  "#.L.###..LGK###.LD#",
  "#....1a.....b2...K#",
  "#N..###K..KM###...#",
  "##.######.#####N..#",
  "##.######E#########",
  "#...K####X#########",
  "#L....###.#########",
  "#K....###.#########",
  "#########.#########",
  "#..N##...L..K######",
  "#Q..##......V#..K.#",
  "#...3c.......#.L..#",
  "#N.K##...........N#",
  "#..L##..L....##.K.#",
  "#########Z#########",
  "#########.#########",
  "#####K.......N##.K#",
  "#.WWL.........##.S#",
  "#SWW.....L....d4..#",
  "#.WW..........##..#",
  "#LWW........J.##K.#",
  "#####.L......K#####",
  "#########.#########",
  "#######U...L#######",
  "#######.....#######",
  "#######f....#######",
  "#########H#########",
  "#########h#########",
  "#K...L.......v..K.#",
  "#.RRRR.RRRRR.RRRR.#",
  "#C...........L...N#",
  "#.RRRRR.RRRR.RRR..#",
  "#...L.......C.....#",
  "#.RRR.RRRRRR.RRRR.#",
  "#K.......L.......C#",
  "#.RRRR.RRRR.RRRR..#",
  "#N..L...C.T.....LK#",
  "#########5#########",
  "#########k#########",
  "#I...L....#N...LK.#",
  "#.##.###..#..###..#",
  "#.#.......#.......#",
  "#.#..L..A.....L.#.#",
  "#.#.......#.....#.#",
  "#....###..#..##.#.#",
  "#K.....L..#.....#I#",
  "#N........#..u...K#",
  "#########6#########",
  "#########e#########",
  "#########...L.....#",
  "#################.#",
  "#.....L.........L.#",
  "#.#################",
  "#...L.......L.....#",
  "#################.#",
  "#########...L.....#",
  "#########F#########",
  "###################",
];
